# This is a basic workflow to help you get started with Actions

name: LaTeX Validation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Compile the LaTeX document with XeLaTeX
    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@1.2.1
      with:
        root_file: demo.tex
        args: -xelatex -file-line-error -interaction=nonstopmode -shell-escape
        extra_system_packages: "py-pygments"
        
    # Upload demo to artifacts if the demo is compiled successfully
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: demo-document
        path: demo.pdf
