# This is a basic workflow to help you get started with Actions

name: LaTeX Release

# Controls when the action will run. Triggers the workflow when a new release is created

on:
  release:
    types: [ created ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Compile the LaTeX document with XeLaTeX
    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@1.2.1
      with:
        root_file: demo.tex
        args: -xelatex -file-line-error -interaction=nonstopmode -shell-escape
        extra_system_packages: "py-pygments"
        
    # Upload demo to releases if the demo is compiled successfully
    - name: Upload release asset
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: demo.pdf
