# This is a basic workflow to help you get started with Actions

name: LaTeX Validation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Compile the LaTeX document with XeLaTeX
    - name: Github Action for LaTeX (Default mode)
      uses: xu-cheng/latex-action@1.2.1
      with:
        root_file: demo-default.tex
        args: -xelatex -file-line-error -interaction=nonstopmode -shell-escape
        extra_system_packages: "py-pygments"
        
    # Upload demo to artifacts if the demo is compiled successfully
    - name: Upload artifacts (Default mode)
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: demo-document-default
        path: demo-default.pdf

    # Change file to dark mode
    - name: Dark mode preparations
      run: sed 's/usecolorstyle{default}/usecolorstyle{dark}/g' demo-default.tex > demo-dark.tex

    # Compile the LaTeX document with XeLaTeX
    - name: Github Action for LaTeX (Dark mode)
      uses: xu-cheng/latex-action@1.2.1
      with:
        root_file: demo-dark.tex
        args: -xelatex -file-line-error -interaction=nonstopmode -shell-escape
        extra_system_packages: "py-pygments"

    # Upload demo to artifacts if the demo is compiled successfully
    - name: Upload artifacts (Dark mode)
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: demo-document-dark
        path: demo-dark.pdf
